#!/bin/bash


chmod +x ~/binder/start.hadoop
chmod +x ~/binder/start.neo4j 


~/binder/start.hadoop && \
sleep 3                && \
~/binder/start.neo4j   &




# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
